package domain

import "time"

// SignalDirection indicates the recommended trade direction.
type SignalDirection string

const (
	SignalBuy  SignalDirection = "BUY"
	SignalSell SignalDirection = "SELL"
	SignalHold SignalDirection = "HOLD"
)

// SignalSource indicates what produced the signal.
type SignalSource string

const (
	SourceNews     SignalSource = "NEWS"
	SourceTA       SignalSource = "TA"
	SourceCombined SignalSource = "COMBINED"
)

// Signal represents a trading signal generated by an analysis engine.
type Signal struct {
	ID        int64          `json:"id" db:"id"`
	Ticker    string         `json:"ticker" db:"ticker"`
	Direction SignalDirection `json:"direction" db:"direction"`
	Source    SignalSource   `json:"source" db:"source"`
	// Strength from 0.0 (weak) to 1.0 (strongest conviction).
	Strength  float64   `json:"strength" db:"strength"`
	Price     float64   `json:"price" db:"price"`
	Reason    string    `json:"reason" db:"reason"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	ExpiresAt time.Time `json:"expires_at" db:"expires_at"`
	// Executed indicates whether this signal was acted upon.
	Executed bool `json:"executed" db:"executed"`

	// NewsSignalMeta is populated when Source == SourceNews.
	NewsSignalMeta *NewsSignalMeta `json:"news_meta,omitempty" db:"-"`
	// TASignalMeta is populated when Source == SourceTA.
	TASignalMeta *TASignalMeta `json:"ta_meta,omitempty" db:"-"`
}

// NewsSignalMeta holds news-specific signal context.
type NewsSignalMeta struct {
	NewsID    int64   `json:"news_id"`
	HeatScore float64 `json:"heat_score"`
	Sentiment float64 `json:"sentiment"`
	Urgency   int     `json:"urgency"`
	Category  string  `json:"category"`
}

// TASignalMeta holds technical-analysis-specific signal context.
type TASignalMeta struct {
	Timeframe  string             `json:"timeframe"` // "1m", "5m", "1h", "1d"
	Indicators map[string]float64 `json:"indicators"`
	Patterns   []string           `json:"patterns,omitempty"`
}
